version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    #environment:
    #  DATABASE_HOST: database
      #POSTGRES_USER: postgres
      #POSTGRES_PASSWORD: postgres
      #POSTGRES_DB: docker_rails
      #WEBPACKER_DEV_SERVER_HOST=webpack_dev_server
      #- WEBPACKER_DEV_SERVER_HOST=webpack_dev_server
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/development/database
      - .env/development/web
  #webpack_dev_server:
  #  build: .
  #  command: ./bin/webpack-dev-server
  #  ports:
  #    - 3035:3035
  #  volumes:
  #    - .:/usr/src/app
  #  #env_file:
  #  #  - .env/development/web
  #  #  - .env/development/database
  #  environment:
  #    - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
  redis:
    image: redis
  database:
    image: postgres
    ports:
      - "5432"
    #environment:
      #POSTGRES_USER: postgres
      #POSTGRES_PASSWORD: postgres
      #POSTGRES_DB: docker_rails
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: