version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docker_rails
    volumes:
      - .:/usr/src/app
    #env_file:
    #  - .env/development/database
    #  - .env/development/web
  redis:
    image: redis
  database:
    image: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docker_rails
    #env_file:
    #  - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: